apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: labs
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-svc:5432/productsdb"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8080"
