server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain application/javascript text/css application/json;

    # Proxy hacia el Service interno de la API (ClusterIP)
    # El browser pide /api/products → nginx lo reenvía a api-svc:3000/api/products
    # api-svc es el nombre del Service ClusterIP — K8s resuelve el DNS internamente
    location /api/ {
        proxy_pass         http://api-svc:3000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    # SPA routing — todas las rutas del frontend van a index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|svg|ico)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
