apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
        - name: api
          image: lab2-7-products-api:v2   # misma imagen del lab 2-7 (con logs)
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "host.docker.internal"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_NAME
---
# ClusterIP — accesible SOLO desde dentro del clúster
# El browser nunca llega aquí directamente
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app: products-api
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
