apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: lab2-8
type: Opaque
data:
  DB_USER:     YWRtaW4=       # admin
  DB_PASSWORD: bmluamExMjM=   # ninja123
  DB_NAME:     bGFiZGI=       # labdb
