server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback: cualquier ruta desconocida sirve index.html (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json;
}
