apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: products-api-hpa
  namespace: labs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: products-api
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60  # Escala cuando CPU supera el 60%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70  # Escala cuando memoria supera el 70%
