apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: lab2-10
type: Opaque
data:
  POSTGRES_USER:     YWRtaW4=       # admin
  POSTGRES_PASSWORD: bmluamExMjM=   # ninja123
  POSTGRES_DB:       bGFiZGI=       # labdb
