apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
# Los valores son base64 — NO es cifrado, solo encoding
# Generar con: echo -n 'valor' | base64
data:
  DB_USER:     YWRtaW4=       # admin
  DB_PASSWORD: bmluamExMjM=   # ninja123
  DB_NAME:     bGFiZGI=       # labdb
