apiVersion: v1
kind: ConfigMap
metadata:
  name: green-html
  namespace: lab3-1
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="es">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>App Verde — Lab 3-1</title>
    </head>
    <body style="background:#065f46;color:white;font-family:Inter,sans-serif;display:flex;justify-content:center;align-items:center;height:100vh;margin:0;flex-direction:column">
      <div style="text-align:center;max-width:500px;padding:40px">
        <div style="font-size:80px">🟢</div>
        <h1 style="font-size:2.5rem;margin:16px 0 8px">App Verde</h1>
        <p style="opacity:.75;font-size:1.1rem;margin:0 0 24px">Kubernetes Lab 3-1 — Ingress path-based routing</p>
        <div style="background:rgba(255,255,255,.12);border-radius:12px;padding:20px 24px">
          <p style="margin:0;font-family:monospace;font-size:1rem">Accediste vía: <strong>/green/</strong></p>
          <p style="margin:8px 0 0;font-size:.85rem;opacity:.7">ClusterIP green-svc → nginx:1.25-alpine</p>
        </div>
      </div>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-app
  namespace: lab3-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green-app
  template:
    metadata:
      labels:
        app: green-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: green-html
---
apiVersion: v1
kind: Service
metadata:
  name: green-svc
  namespace: lab3-1
spec:
  selector:
    app: green-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
