# PersistentVolumeClaim — solicita almacenamiento persistente al clúster
# K8s busca un PersistentVolume disponible (o lo crea via StorageClass)
# y lo "liga" (Bound) a este PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: lab2-9
spec:
  accessModes:
    - ReadWriteOnce        # un solo nodo puede leer/escribir a la vez (suficiente para 1 réplica)
  resources:
    requests:
      storage: 1Gi         # solicita 1 GiB de almacenamiento
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: lab2-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata   # subdirectorio dentro del PVC
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data      # ruta estándar de datos de PostgreSQL
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc                    # referencia al PVC definido arriba
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: lab2-9
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
