apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: lab3-2
type: Opaque
data:
  DB_HOST:     aG9zdC5kb2NrZXIuaW50ZXJuYWw=   # host.docker.internal
  DB_PORT:     NTQzMg==                         # 5432
  DB_USER:     YWRtaW4=                         # admin
  DB_PASSWORD: bmluamExMjM=                     # ninja123
  DB_NAME_CUSTOMERS: Y3VzdG9tZXJzZGI=           # customersdb
  DB_NAME_PRODUCTS:  cHJvZHVjdHNkYg==           # productsdb
